package cn.test.ssm.bean;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.department_id
     *
     * @mbg.generated Mon Feb 25 01:08:28 CST 2019
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.department_name
     *
     * @mbg.generated Mon Feb 25 01:08:28 CST 2019
     */
    private String departmentName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.department_id
     *
     * @return the value of t_department.department_id
     *
     * @mbg.generated Mon Feb 25 01:08:28 CST 2019
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.department_id
     *
     * @param departmentId the value for t_department.department_id
     *
     * @mbg.generated Mon Feb 25 01:08:28 CST 2019
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.department_name
     *
     * @return the value of t_department.department_name
     *
     * @mbg.generated Mon Feb 25 01:08:28 CST 2019
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.department_name
     *
     * @param departmentName the value for t_department.department_name
     *
     * @mbg.generated Mon Feb 25 01:08:28 CST 2019
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }
}